// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ColumnItem: typeof import('./components/Table/src/components/ColumnItem.vue')['default']
    OperationPanel: typeof import('./components/Table/src/components/OperationPanel.vue')['default']
    Src: typeof import('./components/menuTree/src/index.vue')['default']
    TableColumnSetting: typeof import('./components/Table/src/components/TableColumnSetting.vue')['default']
  }
}

export { }
